=== Alen2247208/WSD-Lab-3/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="movielibrary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movie" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="act" type="xs:string" />
                            <xs:element name="dir">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="George Lucas" />
                                        <xs:enumeration value="Steven Spielberg" />
                                        <xs:enumeration value="Christopher Nolan" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="rat">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:pattern value="[2-5]"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="rd" type="xs:date" />
                            <xs:element name="cost">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:pattern value="[0-9]{8}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Alen2247208/WSD-Lab-3/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="index.xsl" type="text/xsl"?>
<movielibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd">
    <movie>
        <name>Aliens</name>
        <act>Sigori</act>
        <dir>Steven Spielberg</dir>
        <rat>4</rat>
        <rd>1999-08-09</rd>
        <cost>10000000</cost>
    </movie>
    <movie>
        <name>Total Recall</name>
        <act>Arnold</act>
        <dir>George Lucas</dir>
        <rat>2</rat>
        <rd>2010-06-10</rd>
        <cost>20000000</cost>
    </movie>
    <movie>
        <name>Inception</name>
        <act>Leo</act>
        <dir>Steven Spielberg</dir>
        <rat>3</rat>
        <rd>2003-11-17</rd>
        <cost>50000000</cost>
    </movie>
    <movie>
        <name>Tenet</name>
        <act>Robert</act>
        <dir>George Lucas</dir>
        <rat>2</rat>
        <rd>1990-06-28</rd>
        <cost>20000000</cost>
    </movie>
    <movie>
        <name>Prestige</name>
        <act>Christian</act>
        <dir>Steven Spielberg</dir>
        <rat>5</rat>
        <rd>1999-11-12</rd>
        <cost>15000000</cost>
    </movie>
    <movie>
        <name>Avengers</name>
        <act>Chris Brown</act>
        <dir>Christopher Nolan</dir>
        <rat>3</rat>
        <rd>2006-06-16</rd>
        <cost>20000000</cost>
    </movie>
    <movie>
        <name>Iron Man</name>
        <act>Robert Downey</act>
        <dir>George Lucas</dir>
        <rat>5</rat>
        <rd>2009-08-20</rd>
        <cost>30000000</cost>
    </movie>
    <movie>
        <name>Wonder Women</name>
        <act>Alia Joseph</act>
        <dir>Christopher Nolan</dir>
        <rat>4</rat>
        <rd>2017-02-19</rd>
        <cost>45000000</cost>
    </movie>
</movielibrary>
